(ns pinkgorilla.nrepl-specs-test
  (:require
   #?(:cljs [cljs.test :refer-macros [deftest is]]
      :clj  [clojure.test :refer [deftest is]])
;   #?(:cljs [pinkgorilla.test-macros :refer-macros [assert-captured-test-results]]
;      :clj  [pinkgorilla.test-macros :refer [assert-captured-test-results]])
   [clojure.spec.alpha :as s]
   ; bring the specs into scope:
   [pinkgorilla.kernel.nrepl-specs]))

(def done-msg
  {:session "7362f58e-b613-46f8-853c-efcd8b61a590"
   :id "97bae174-7736-4911-a9b1-c7f2f7049e69"
   :status #{:done}})

(def ex-msg
  {:session "7362f58e-b613-46f8-853c-efcd8b61a590"
   :id "d5d598e3-ec20-4bf1-b6b9-af6329ac58c1"
   :err "Execution error (IllegalArgumentException) at clojure.core.async.impl.protocols/eval88015$fn$G (protocols.clj:43).\nNo implementation of method: :exec of protocol: #'clojure.core.async.impl.protocols/Executor found for class: clojure.core.async.impl.exec.threadpool$thread_pool_executor$reify__933\n"})

(def ex-root-ex-msg
  {:session "7362f58e-b613-46f8-853c-efcd8b61a590"
   :id "d5d598e3-ec20-4bf1-b6b9-af6329ac58c1"
   :status #{:eval-error}
   :ex "class clojure.lang.Compiler$CompilerException"
   :root-ex "class clojure.lang.Compiler$CompilerException"})

(def stacktrace-msg
  {:id "b1a8e582-57ba-4cdc-a17b-5a608776bedc"
   :session "d7cecfd8-b1e0-44d7-ae9c-1d77e27f3ccc"
   :class "java.lang.Exception"
   :message "Some text"
   :stacktrace
   '({:fn "eval64540", :method "invokeStatic", :ns "user", :name "user$eval64540/invokeStatic", :file "NO_SOURCE_FILE", :type :clj, :file-url nil, :line 1, :var "user/eval64540", :class "user$eval64540", :flags #{:repl :clj}}
     {:fn "eval64540", :method "invoke", :ns "user", :name "user$eval64540/invoke", :file "NO_SOURCE_FILE", :type :clj, :file-url nil, :line 1, :var "user/eval64540", :class "user$eval64540", :flags #{:dup :repl :clj}}
     {:name "clojure.lang.Compiler/eval", :file "Compiler.java", :line 7177, :class "clojure.lang.Compiler", :method "eval", :type :java, :flags #{:tooling :java}, :file-url nil}
     {:name "clojure.lang.Compiler/eval", :file "Compiler.java", :line 7132, :class "clojure.lang.Compiler", :method "eval", :type :java, :flags #{:dup :tooling :java}, :file-url nil}
     {:fn "eval", :method "invokeStatic", :ns "clojure.core", :name "clojure.core$eval/invokeStatic", :file "core.clj", :type :clj, :file-url "jar:file:/home/andreas/.m2/repository/org/clojure/clojure/1.10.1/clojure-1.10.1.jar!/clojure/core.clj", :line 3214, :var "clojure.core/eval", :class "clojure.core$eval", :flags #{:clj}}
     {:fn "eval", :method "invoke", :ns "clojure.core", :name "clojure.core$eval/invoke", :file "core.clj", :type :clj, :file-url "jar:file:/home/andreas/.m2/repository/org/clojure/clojure/1.10.1/clojure-1.10.1.jar!/clojure/core.clj", :line 3210, :var "clojure.core/eval", :class "clojure.core$eval", :flags #{:clj}}
     {:fn "repl/read-eval-print/fn", :method "invoke", :ns "clojure.main", :name "clojure.main$repl$read_eval_print__9086$fn__9089/invoke", :file "main.clj", :type :clj, :file-url "jar:file:/home/andreas/.m2/repository/org/clojure/clojure/1.10.1/clojure-1.10.1.jar!/clojure/main.clj", :line 437, :var "clojure.main/repl", :class "clojure.main$repl$read_eval_print__9086$fn__9089", :flags #{:clj}}
     {:fn "repl/read-eval-print", :method "invoke", :ns "clojure.main", :name "clojure.main$repl$read_eval_print__9086/invoke", :file "main.clj", :type :clj, :file-url "jar:file:/home/andreas/.m2/repository/org/clojure/clojure/1.10.1/clojure-1.10.1.jar!/clojure/main.clj", :line 437, :var "clojure.main/repl", :class "clojure.main$repl$read_eval_print__9086", :flags #{:dup :clj}}
     {:fn "repl/fn", :method "invoke", :ns "clojure.main", :name "clojure.main$repl$fn__9095/invoke", :file "main.clj", :type :clj, :file-url "jar:file:/home/andreas/.m2/repository/org/clojure/clojure/1.10.1/clojure-1.10.1.jar!/clojure/main.clj", :line 458, :var "clojure.main/repl", :class "clojure.main$repl$fn__9095", :flags #{:clj}}
     {:fn "repl", :method "invokeStatic", :ns "clojure.main", :name "clojure.main$repl/invokeStatic", :file "main.clj", :type :clj, :file-url "jar:file:/home/andreas/.m2/repository/org/clojure/clojure/1.10.1/clojure-1.10.1.jar!/clojure/main.clj", :line 458, :var "clojure.main/repl", :class "clojure.main$repl", :flags #{:dup :clj}}
     {:fn "repl", :method "doInvoke", :ns "clojure.main", :name "clojure.main$repl/doInvoke", :file "main.clj", :type :clj, :file-url "jar:file:/home/andreas/.m2/repository/org/clojure/clojure/1.10.1/clojure-1.10.1.jar!/clojure/main.clj", :line 368, :var "clojure.main/repl", :class "clojure.main$repl", :flags #{:clj}}
     {:name "clojure.lang.RestFn/invoke", :file "RestFn.java", :line 1523, :class "clojure.lang.RestFn", :method "invoke", :type :java, :flags #{:java}, :file-url nil} {:fn "evaluate", :method "invokeStatic", :ns "nrepl.middleware.interruptible-eval", :name "nrepl.middleware.interruptible_eval$evaluate/invokeStatic", :file "interruptible_eval.clj", :type :clj, :file-url "jar:file:/home/andreas/.m2/repository/nrepl/nrepl/0.6.0/nrepl-0.6.0.jar!/nrepl/middleware/interruptible_eval.clj", :line 79, :var "nrepl.middleware.interruptible-eval/evaluate", :class "nrepl.middleware.interruptible_eval$evaluate", :flags #{:tooling :clj}}
     {:fn "evaluate", :method "invoke", :ns "nrepl.middleware.interruptible-eval", :name "nrepl.middleware.interruptible_eval$evaluate/invoke", :file "interruptible_eval.clj", :type :clj, :file-url "jar:file:/home/andreas/.m2/repository/nrepl/nrepl/0.6.0/nrepl-0.6.0.jar!/nrepl/middleware/interruptible_eval.clj", :line 55, :var "nrepl.middleware.interruptible-eval/evaluate", :class "nrepl.middleware.interruptible_eval$evaluate", :flags #{:tooling :clj}}
     {:fn "interruptible-eval/fn/fn", :method "invoke", :ns "nrepl.middleware.interruptible-eval", :name "nrepl.middleware.interruptible_eval$interruptible_eval$fn__24364$fn__24368/invoke", :file "interruptible_eval.clj", :type :clj, :file-url "jar:file:/home/andreas/.m2/repository/nrepl/nrepl/0.6.0/nrepl-0.6.0.jar!/nrepl/middleware/interruptible_eval.clj", :line 142, :var "nrepl.middleware.interruptible-eval/interruptible-eval", :class "nrepl.middleware.interruptible_eval$interruptible_eval$fn__24364$fn__24368", :flags #{:tooling :clj}}
     {:name "clojure.lang.AFn/run", :file "AFn.java", :line 22, :class "clojure.lang.AFn", :method "run", :type :java, :flags #{:java}, :file-url nil} {:fn "session-exec/main-loop/fn", :method "invoke", :ns "nrepl.middleware.session", :name "nrepl.middleware.session$session_exec$main_loop__24465$fn__24469/invoke", :file "session.clj", :type :clj, :file-url "jar:file:/home/andreas/.m2/repository/nrepl/nrepl/0.6.0/nrepl-0.6.0.jar!/nrepl/middleware/session.clj", :line 171, :var "nrepl.middleware.session/session-exec", :class "nrepl.middleware.session$session_exec$main_loop__24465$fn__24469", :flags #{:tooling :clj}}
     {:fn "session-exec/main-loop", :method "invoke", :ns "nrepl.middleware.session", :name "nrepl.middleware.session$session_exec$main_loop__24465/invoke", :file "session.clj", :type :clj, :file-url "jar:file:/home/andreas/.m2/repository/nrepl/nrepl/0.6.0/nrepl-0.6.0.jar!/nrepl/middleware/session.clj", :line 170, :var "nrepl.middleware.session/session-exec", :class "nrepl.middleware.session$session_exec$main_loop__24465", :flags #{:tooling :clj}}
     {:name "clojure.lang.AFn/run", :file "AFn.java", :line 22, :class "clojure.lang.AFn", :method "run", :type :java, :flags #{:java}, :file-url nil} {:name "java.lang.Thread/run", :file "Thread.java", :line 748, :class "java.lang.Thread", :method "run", :type :java, :flags #{:java}, :file-url nil})})

(def stacktrace-with-location
  {:id "97bae174-7736-4911-a9b1-c7f2f7049e69"
   :session "7362f58e-b613-46f8-853c-efcd8b61a590"
   :class "clojure.lang.Compiler$CompilerException"
   :path "alphavantage.clj"
   :file "alphavantage.clj"
   :file-url nil
   :column 3
   :line 68
   :message "Syntax error macroexpanding at (alphavantage.clj:68:3)."
   :stacktrace '({:name "clojure.lang.Compiler$InvokeExpr/eval", :file "Compiler.java", :line 3707, :class "clojure.lang.Compiler$InvokeExpr", :method "eval", :type :java, :flags #{:tooling :java}, :file-url nil}
                 {:name "clojure.lang.Compiler$DefExpr/eval", :file "Compiler.java", :line 457, :class "clojure.lang.Compiler$DefExpr", :method "eval", :type :java, :flags #{:tooling :java}, :file-url nil}
                 {:name "clojure.lang.Compiler/eval", :file "Compiler.java", :line 7182, :class "clojure.lang.Compiler", :method "eval", :type :java, :flags #{:tooling :java}, :file-url nil}
                 {:name "clojure.lang.Compiler/load", :file "Compiler.java", :line 7636, :class "clojure.lang.Compiler", :method "load", :type :java, :flags #{:tooling :java}, :file-url nil}
                 {:name "clojure.lang.RT/loadResourceScript", :file "RT.java", :line 381, :class "clojure.lang.RT", :method "loadResourceScript", :type :java, :flags #{:java}, :file-url nil}
                 {:name "clojure.lang.RT/loadResourceScript", :file "RT.java", :line 372, :class "clojure.lang.RT", :method "loadResourceScript", :type :java, :flags #{:dup :java}, :file-url nil}
                 {:name "clojure.lang.RT/load", :file "RT.java", :line 459, :class "clojure.lang.RT", :method "load", :type :java, :flags #{:java}, :file-url nil}
                 {:name "clojure.lang.RT/load", :file "RT.java", :line 424, :class "clojure.lang.RT", :method "load", :type :java, :flags #{:dup :java}, :file-url nil}
                 {:fn "load/fn", :method "invoke", :ns "clojure.core", :name "clojure.core$load$fn__6839/invoke", :file "core.clj", :type :clj, :file-url "jar:file:/home/andreas/.m2/repository/org/clojure/clojure/1.10.1/clojure-1.10.1.jar!/clojure/core.clj", :line 6126, :var "clojure.core/load", :class "clojure.core$load$fn__6839", :flags #{:clj}}
                 {:fn "load", :method "invokeStatic", :ns "clojure.core", :name "clojure.core$load/invokeStatic", :file "core.clj", :type :clj, :file-url "jar:file:/home/andreas/.m2/repository/org/clojure/clojure/1.10.1/clojure-1.10.1.jar!/clojure/core.clj", :line 6125, :var "clojure.core/load", :class "clojure.core$load", :flags #{:clj}}
                 {:fn "load", :method "doInvoke", :ns "clojure.core", :name "clojure.core$load/doInvoke", :file "core.clj", :type :clj, :file-url "jar:file:/home/andreas/.m2/repository/org/clojure/clojure/1.10.1/clojure-1.10.1.jar!/clojure/core.clj", :line 6109, :var "clojure.core/load", :class "clojure.core$load", :flags #{:clj}}
                 {:name "clojure.lang.RestFn/invoke", :file "RestFn.java", :line 408, :class "clojure.lang.RestFn", :method "invoke", :type :java, :flags #{:java}, :file-url nil}
                 {:fn "load-one", :method "invokeStatic", :ns "clojure.core", :name "clojure.core$load_one/invokeStatic", :file "core.clj", :type :clj, :file-url "jar:file:/home/andreas/.m2/repository/org/clojure/clojure/1.10.1/clojure-1.10.1.jar!/clojure/core.clj", :line 5908, :var "clojure.core/load-one", :class "clojure.core$load_one", :flags #{:clj}}
                 {:fn "load-one", :method "invoke", :ns "clojure.core", :name "clojure.core$load_one/invoke", :file "core.clj", :type :clj, :file-url "jar:file:/home/andreas/.m2/repository/org/clojure/clojure/1.10.1/clojure-1.10.1.jar!/clojure/core.clj", :line 5903, :var "clojure.core/load-one", :class "clojure.core$load_one", :flags #{:clj}}
                 {:fn "load-lib/fn", :method "invoke", :ns "clojure.core", :name "clojure.core$load_lib$fn__6780/invoke", :file "core.clj", :type :clj, :file-url "jar:file:/home/andreas/.m2/repository/org/clojure/clojure/1.10.1/clojure-1.10.1.jar!/clojure/core.clj", :line 5948, :var "clojure.core/load-lib", :class "clojure.core$load_lib$fn__6780", :flags #{:clj}}
                 {:fn "load-lib", :method "invokeStatic", :ns "clojure.core", :name "clojure.core$load_lib/invokeStatic", :file "core.clj", :type :clj, :file-url "jar:file:/home/andreas/.m2/repository/org/clojure/clojure/1.10.1/clojure-1.10.1.jar!/clojure/core.clj", :line 5947, :var "clojure.core/load-lib", :class "clojure.core$load_lib", :flags #{:clj}}
                 {:fn "load-lib", :method "doInvoke", :ns "clojure.core", :name "clojure.core$load_lib/doInvoke", :file "core.clj", :type :clj, :file-url "jar:file:/home/andreas/.m2/repository/org/clojure/clojure/1.10.1/clojure-1.10.1.jar!/clojure/core.clj", :line 5928, :var "clojure.core/load-lib", :class "clojure.core$load_lib", :flags #{:clj}}
                 {:name "clojure.lang.RestFn/applyTo", :file "RestFn.java", :line 142, :class "clojure.lang.RestFn", :method "applyTo", :type :java, :flags #{:java}, :file-url nil}
                 {:fn "apply", :method "invokeStatic", :ns "clojure.core", :name "clojure.core$apply/invokeStatic", :file "core.clj", :type :clj, :file-url "jar:file:/home/andreas/.m2/repository/org/clojure/clojure/1.10.1/clojure-1.10.1.jar!/clojure/core.clj", :line 667, :var "clojure.core/apply", :class "clojure.core$apply", :flags #{:clj}}
                 {:fn "load-libs", :method "invokeStatic", :ns "clojure.core", :name "clojure.core$load_libs/invokeStatic", :file "core.clj", :type :clj, :file-url "jar:file:/home/andreas/.m2/repository/org/clojure/clojure/1.10.1/clojure-1.10.1.jar!/clojure/core.clj", :line 5985, :var "clojure.core/load-libs", :class "clojure.core$load_libs", :flags #{:clj}}
                 {:fn "load-libs", :method "doInvoke", :ns "clojure.core", :name "clojure.core$load_libs/doInvoke", :file "core.clj", :type :clj, :file-url "jar:file:/home/andreas/.m2/repository/org/clojure/clojure/1.10.1/clojure-1.10.1.jar!/clojure/core.clj", :line 5969, :var "clojure.core/load-libs", :class "clojure.core$load_libs", :flags #{:clj}}
                 {:name "clojure.lang.RestFn/applyTo", :file "RestFn.java", :line 137, :class "clojure.lang.RestFn", :method "applyTo", :type :java, :flags #{:java}, :file-url nil}
                 {:fn "apply", :method "invokeStatic", :ns "clojure.core", :name "clojure.core$apply/invokeStatic", :file "core.clj", :type :clj, :file-url "jar:file:/home/andreas/.m2/repository/org/clojure/clojure/1.10.1/clojure-1.10.1.jar!/clojure/core.clj", :line 667, :var "clojure.core/apply", :class "clojure.core$apply", :flags #{:clj}}
                 {:fn "require", :method "invokeStatic", :ns "clojure.core", :name "clojure.core$require/invokeStatic", :file "core.clj", :type :clj, :file-url "jar:file:/home/andreas/.m2/repository/org/clojure/clojure/1.10.1/clojure-1.10.1.jar!/clojure/core.clj", :line 6007, :var "clojure.core/require", :class "clojure.core$require", :flags #{:clj}}
                 {:fn "require", :method "doInvoke", :ns "clojure.core", :name "clojure.core$require/doInvoke", :file "core.clj", :type :clj, :file-url "jar:file:/home/andreas/.m2/repository/org/clojure/clojure/1.10.1/clojure-1.10.1.jar!/clojure/core.clj", :line 6007, :var "clojure.core/require", :class "clojure.core$require", :flags #{:dup :clj}}
                 {:name "clojure.lang.RestFn/invoke", :file "RestFn.java", :line 805, :class "clojure.lang.RestFn", :method "invoke", :type :java, :flags #{:java}, :file-url nil}
                 {:fn "eval96277/loading--auto--", :method "invoke", :ns "dynalloc.chevvy", :name "dynalloc.chevvy$eval96277$loading__6721__auto____96278/invoke", :file "NO_SOURCE_FILE", :type :clj, :file-url nil, :line 1, :var "dynalloc.chevvy/eval96277", :class "dynalloc.chevvy$eval96277$loading__6721__auto____96278", :flags #{:repl :clj}}
                 {:fn "eval96277", :method "invokeStatic", :ns "dynalloc.chevvy", :name "dynalloc.chevvy$eval96277/invokeStatic", :file "NO_SOURCE_FILE", :type :clj, :file-url nil, :line 1, :var "dynalloc.chevvy/eval96277", :class "dynalloc.chevvy$eval96277", :flags #{:dup :repl :clj}}
                 {:fn "eval96277", :method "invoke", :ns "dynalloc.chevvy", :name "dynalloc.chevvy$eval96277/invoke", :file "NO_SOURCE_FILE", :type :clj, :file-url nil, :line 1, :var "dynalloc.chevvy/eval96277", :class "dynalloc.chevvy$eval96277", :flags #{:dup :repl :clj}}
                 {:name "clojure.lang.Compiler/eval", :file "Compiler.java", :line 7177, :class "clojure.lang.Compiler", :method "eval", :type :java, :flags #{:tooling :java}, :file-url nil}
                 {:name "clojure.lang.Compiler/eval", :file "Compiler.java", :line 7166, :class "clojure.lang.Compiler", :method "eval", :type :java, :flags #{:dup :tooling :java}, :file-url nil}
                 {:name "clojure.lang.Compiler/eval", :file "Compiler.java", :line 7132, :class "clojure.lang.Compiler", :method "eval", :type :java, :flags #{:dup :tooling :java}, :file-url nil}
                 {:fn "eval", :method "invokeStatic", :ns "clojure.core", :name "clojure.core$eval/invokeStatic", :file "core.clj", :type :clj, :file-url "jar:file:/home/andreas/.m2/repository/org/clojure/clojure/1.10.1/clojure-1.10.1.jar!/clojure/core.clj", :line 3214, :var "clojure.core/eval", :class "clojure.core$eval", :flags #{:clj}}
                 {:fn "eval", :method "invoke", :ns "clojure.core", :name "clojure.core$eval/invoke", :file "core.clj", :type :clj, :file-url "jar:file:/home/andreas/.m2/repository/org/clojure/clojure/1.10.1/clojure-1.10.1.jar!/clojure/core.clj", :line 3210, :var "clojure.core/eval", :class "clojure.core$eval", :flags #{:clj}}
                 {:fn "repl/read-eval-print/fn", :method "invoke", :ns "clojure.main", :name "clojure.main$repl$read_eval_print__9086$fn__9089/invoke", :file "main.clj", :type :clj, :file-url "jar:file:/home/andreas/.m2/repository/org/clojure/clojure/1.10.1/clojure-1.10.1.jar!/clojure/main.clj", :line 437, :var "clojure.main/repl", :class "clojure.main$repl$read_eval_print__9086$fn__9089", :flags #{:clj}}
                 {:fn "repl/read-eval-print", :method "invoke", :ns "clojure.main", :name "clojure.main$repl$read_eval_print__9086/invoke", :file "main.clj", :type :clj, :file-url "jar:file:/home/andreas/.m2/repository/org/clojure/clojure/1.10.1/clojure-1.10.1.jar!/clojure/main.clj", :line 437, :var "clojure.main/repl", :class "clojure.main$repl$read_eval_print__9086", :flags #{:dup :clj}}
                 {:fn "repl/fn", :method "invoke", :ns "clojure.main", :name "clojure.main$repl$fn__9095/invoke", :file "main.clj", :type :clj, :file-url "jar:file:/home/andreas/.m2/repository/org/clojure/clojure/1.10.1/clojure-1.10.1.jar!/clojure/main.clj", :line 458, :var "clojure.main/repl", :class "clojure.main$repl$fn__9095", :flags #{:clj}}
                 {:fn "repl", :method "invokeStatic", :ns "clojure.main", :name "clojure.main$repl/invokeStatic", :file "main.clj", :type :clj, :file-url "jar:file:/home/andreas/.m2/repository/org/clojure/clojure/1.10.1/clojure-1.10.1.jar!/clojure/main.clj", :line 458, :var "clojure.main/repl", :class "clojure.main$repl", :flags #{:dup :clj}}
                 {:fn "repl", :method "doInvoke", :ns "clojure.main", :name "clojure.main$repl/doInvoke", :file "main.clj", :type :clj, :file-url "jar:file:/home/andreas/.m2/repository/org/clojure/clojure/1.10.1/clojure-1.10.1.jar!/clojure/main.clj", :line 368, :var "clojure.main/repl", :class "clojure.main$repl", :flags #{:clj}}
                 {:name "clojure.lang.RestFn/invoke", :file "RestFn.java", :line 1523, :class "clojure.lang.RestFn", :method "invoke", :type :java, :flags #{:java}, :file-url nil}
                 {:fn "evaluate", :method "invokeStatic", :ns "nrepl.middleware.interruptible-eval", :name "nrepl.middleware.interruptible_eval$evaluate/invokeStatic", :file "interruptible_eval.clj", :type :clj, :file-url "jar:file:/home/andreas/.m2/repository/nrepl/nrepl/0.6.0/nrepl-0.6.0.jar!/nrepl/middleware/interruptible_eval.clj", :line 79, :var "nrepl.middleware.interruptible-eval/evaluate", :class "nrepl.middleware.interruptible_eval$evaluate", :flags #{:tooling :clj}}
                 {:fn "evaluate", :method "invoke", :ns "nrepl.middleware.interruptible-eval", :name "nrepl.middleware.interruptible_eval$evaluate/invoke", :file "interruptible_eval.clj", :type :clj, :file-url "jar:file:/home/andreas/.m2/repository/nrepl/nrepl/0.6.0/nrepl-0.6.0.jar!/nrepl/middleware/interruptible_eval.clj", :line 55, :var "nrepl.middleware.interruptible-eval/evaluate", :class "nrepl.middleware.interruptible_eval$evaluate", :flags #{:tooling :clj}}
                 {:fn "interruptible-eval/fn/fn", :method "invoke", :ns "nrepl.middleware.interruptible-eval", :name "nrepl.middleware.interruptible_eval$interruptible_eval$fn__24364$fn__24368/invoke", :file "interruptible_eval.clj", :type :clj, :file-url "jar:file:/home/andreas/.m2/repository/nrepl/nrepl/0.6.0/nrepl-0.6.0.jar!/nrepl/middleware/interruptible_eval.clj", :line 142, :var "nrepl.middleware.interruptible-eval/interruptible-eval", :class "nrepl.middleware.interruptible_eval$interruptible_eval$fn__24364$fn__24368", :flags #{:tooling :clj}}
                 {:name "clojure.lang.AFn/run", :file "AFn.java", :line 22, :class "clojure.lang.AFn", :method "run", :type :java, :flags #{:java}, :file-url nil}
                 {:fn "session-exec/main-loop/fn", :method "invoke", :ns "nrepl.middleware.session", :name "nrepl.middleware.session$session_exec$main_loop__24465$fn__24469/invoke", :file "session.clj", :type :clj, :file-url "jar:file:/home/andreas/.m2/repository/nrepl/nrepl/0.6.0/nrepl-0.6.0.jar!/nrepl/middleware/session.clj", :line 171, :var "nrepl.middleware.session/session-exec", :class "nrepl.middleware.session$session_exec$main_loop__24465$fn__24469", :flags #{:tooling :clj}}
                 {:fn "session-exec/main-loop", :method "invoke", :ns "nrepl.middleware.session", :name "nrepl.middleware.session$session_exec$main_loop__24465/invoke", :file "session.clj", :type :clj, :file-url "jar:file:/home/andreas/.m2/repository/nrepl/nrepl/0.6.0/nrepl-0.6.0.jar!/nrepl/middleware/session.clj", :line 170, :var "nrepl.middleware.session/session-exec", :class "nrepl.middleware.session$session_exec$main_loop__24465", :flags #{:tooling :clj}}
                 {:name "clojure.lang.AFn/run", :file "AFn.java", :line 22, :class "clojure.lang.AFn", :method "run", :type :java, :flags #{:java}, :file-url nil}
                 {:name "java.lang.Thread/run", :file "Thread.java", :line 748, :class "java.lang.Thread", :method "run", :type :java, :flags #{:java}, :file-url nil})
   :location {:clojure.error/line 68
              :clojure.error/column 3
              :clojure.error/phase :execution
              :clojure.error/source "alphavantage.clj"}
   :data "{:clojure.error/phase :execution, :clojure.error/line 68, :clojure.error/column 3, :clojure.error/source \"alphavantage.clj\"}"})

(def stacktrace-2-msg
  {:session "7362f58e-b613-46f8-853c-efcd8b61a590"
   :id "97bae174-7736-4911-a9b1-c7f2f7049e69"
   :class "java.lang.IllegalArgumentException"
   :message "No implementation of method: :exec of protocol: #'clojure.core.async.impl.protocols/Executor found for class: clojure.core.async.impl.exec.threadpool$thread_pool_executor$reify__933"
   :stacktrace '({:fn "-cache-protocol-fn", :method "invokeStatic", :ns "clojure.core", :name "clojure.core$_cache_protocol_fn/invokeStatic", :file "core_deftype.clj", :type :clj, :file-url "jar:file:/home/andreas/.m2/repository/org/clojure/clojure/1.10.1/clojure-1.10.1.jar!/clojure/core_deftype.clj", :line 583, :var "clojure.core/-cache-protocol-fn", :class "clojure.core$_cache_protocol_fn", :flags #{:clj}}
                 {:fn "-cache-protocol-fn", :method "invoke", :ns "clojure.core", :name "clojure.core$_cache_protocol_fn/invoke", :file "core_deftype.clj", :type :clj, :file-url "jar:file:/home/andreas/.m2/repository/org/clojure/clojure/1.10.1/clojure-1.10.1.jar!/clojure/core_deftype.clj", :line 575, :var "clojure.core/-cache-protocol-fn", :class "clojure.core$_cache_protocol_fn", :flags #{:clj}}
                 {:fn "eval88015/fn/G", :method "invoke", :ns "clojure.core.async.impl.protocols", :name "clojure.core.async.impl.protocols$eval88015$fn__88016$G__88006__88023/invoke", :file "protocols.clj", :type :clj, :file-url "jar:file:/home/andreas/.m2/repository/org/clojure/core.async/1.1.582/core.async-1.1.582.jar!/clojure/core/async/impl/protocols.clj", :line 43, :var "clojure.core.async.impl.protocols/eval88015", :class "clojure.core.async.impl.protocols$eval88015$fn__88016$G__88006__88023", :flags #{:clj}}
                 {:fn "run", :method "invokeStatic", :ns "clojure.core.async.impl.dispatch", :name "clojure.core.async.impl.dispatch$run/invokeStatic", :file "dispatch.clj", :type :clj, :file-url "jar:file:/home/andreas/.m2/repository/org/clojure/core.async/1.1.582/core.async-1.1.582.jar!/clojure/core/async/impl/dispatch.clj", :line 35, :var "clojure.core.async.impl.dispatch/run", :class "clojure.core.async.impl.dispatch$run", :flags #{:clj}}
                 {:fn "run", :method "invoke", :ns "clojure.core.async.impl.dispatch", :name "clojure.core.async.impl.dispatch$run/invoke", :file "dispatch.clj", :type :clj, :file-url "jar:file:/home/andreas/.m2/repository/org/clojure/core.async/1.1.582/core.async-1.1.582.jar!/clojure/core/async/impl/dispatch.clj", :line 32, :var "clojure.core.async.impl.dispatch/run", :class "clojure.core.async.impl.dispatch$run", :flags #{:clj}}
                 {:fn "chan-throttler*", :method "invokeStatic", :ns "throttler.core", :name "throttler.core$chan_throttler_STAR_/invokeStatic", :file "core.clj", :type :clj, :file-url "jar:file:/home/andreas/.m2/repository/org/pinkgorilla/throttler/1.0.1/throttler-1.0.1.jar!/throttler/core.clj", :line 35, :var "throttler.core/chan-throttler*", :class "throttler.core$chan_throttler_STAR_", :flags #{:clj}}
                 {:fn "chan-throttler*", :method "invoke", :ns "throttler.core", :name "throttler.core$chan_throttler_STAR_/invoke", :file "core.clj", :type :clj, :file-url "jar:file:/home/andreas/.m2/repository/org/pinkgorilla/throttler/1.0.1/throttler-1.0.1.jar!/throttler/core.clj", :line 27, :var "throttler.core/chan-throttler*", :class "throttler.core$chan_throttler_STAR_", :flags #{:clj}}
                 {:fn "chan-throttler", :method "invokeStatic", :ns "throttler.core", :name "throttler.core$chan_throttler/invokeStatic", :file "core.clj", :type :clj, :file-url "jar:file:/home/andreas/.m2/repository/org/pinkgorilla/throttler/1.0.1/throttler-1.0.1.jar!/throttler/core.clj", :line 85, :var "throttler.core/chan-throttler", :class "throttler.core$chan_throttler", :flags #{:clj}}
                 {:fn "chan-throttler", :method "invoke", :ns "throttler.core", :name "throttler.core$chan_throttler/invoke", :file "core.clj", :type :clj, :file-url "jar:file:/home/andreas/.m2/repository/org/pinkgorilla/throttler/1.0.1/throttler-1.0.1.jar!/throttler/core.clj", :line 57, :var "throttler.core/chan-throttler", :class "throttler.core$chan_throttler", :flags #{:clj}}
                 {:fn "throttle-chan", :method "invokeStatic", :ns "throttler.core", :name "throttler.core$throttle_chan/invokeStatic", :file "core.clj", :type :clj, :file-url "jar:file:/home/andreas/.m2/repository/org/pinkgorilla/throttler/1.0.1/throttler-1.0.1.jar!/throttler/core.clj", :line 115, :var "throttler.core/throttle-chan", :class "throttler.core$throttle_chan", :flags #{:clj}}
                 {:fn "throttle-chan", :method "invoke", :ns "throttler.core", :name "throttler.core$throttle_chan/invoke", :file "core.clj", :type :clj, :file-url "jar:file:/home/andreas/.m2/repository/org/pinkgorilla/throttler/1.0.1/throttler-1.0.1.jar!/throttler/core.clj", :line 87, :var "throttler.core/throttle-chan", :class "throttler.core$throttle_chan", :flags #{:clj}}
                 {:fn "fn-throttler", :method "invokeStatic", :ns "throttler.core", :name "throttler.core$fn_throttler/invokeStatic", :file "core.clj", :type :clj, :file-url "jar:file:/home/andreas/.m2/repository/org/pinkgorilla/throttler/1.0.1/throttler-1.0.1.jar!/throttler/core.clj", :line 154, :var "throttler.core/fn-throttler", :class "throttler.core$fn_throttler", :flags #{:clj}}
                 {:fn "fn-throttler", :method "invoke", :ns "throttler.core", :name "throttler.core$fn_throttler/invoke", :file "core.clj", :type :clj, :file-url "jar:file:/home/andreas/.m2/repository/org/pinkgorilla/throttler/1.0.1/throttler-1.0.1.jar!/throttler/core.clj", :line 117, :var "throttler.core/fn-throttler", :class "throttler.core$fn_throttler", :flags #{:clj}}
                 {:fn "throttle-fn", :method "invokeStatic", :ns "throttler.core", :name "throttler.core$throttle_fn/invokeStatic", :file "core.clj", :type :clj, :file-url "jar:file:/home/andreas/.m2/repository/org/pinkgorilla/throttler/1.0.1/throttler-1.0.1.jar!/throttler/core.clj", :line 182, :var "throttler.core/throttle-fn", :class "throttler.core$throttle_fn", :flags #{:clj}}
                 {:fn "throttle-fn", :method "invoke", :ns "throttler.core", :name "throttler.core$throttle_fn/invoke", :file "core.clj", :type :clj, :file-url "jar:file:/home/andreas/.m2/repository/org/pinkgorilla/throttler/1.0.1/throttler-1.0.1.jar!/throttler/core.clj", :line 170, :var "throttler.core/throttle-fn", :class "throttler.core$throttle_fn", :flags #{:clj}}
                 {:fn "throttle-fn", :method "invokeStatic", :ns "throttler.core", :name "throttler.core$throttle_fn/invokeStatic", :file "core.clj", :type :clj, :file-url "jar:file:/home/andreas/.m2/repository/org/pinkgorilla/throttler/1.0.1/throttler-1.0.1.jar!/throttler/core.clj", :line 179, :var "throttler.core/throttle-fn", :class "throttler.core$throttle_fn", :flags #{:clj}}
                 {:fn "throttle-fn", :method "invoke", :ns "throttler.core", :name "throttler.core$throttle_fn/invoke", :file "core.clj", :type :clj, :file-url "jar:file:/home/andreas/.m2/repository/org/pinkgorilla/throttler/1.0.1/throttler-1.0.1.jar!/throttler/core.clj", :line 170, :var "throttler.core/throttle-fn", :class "throttler.core$throttle_fn", :flags #{:clj}}
                 {:name "clojure.lang.AFn/applyToHelper", :file "AFn.java", :line 160, :class "clojure.lang.AFn", :method "applyToHelper", :type :java, :flags #{:java}, :file-url nil}
                 {:name "clojure.lang.AFn/applyTo", :file "AFn.java", :line 144, :class "clojure.lang.AFn", :method "applyTo", :type :java, :flags #{:java}, :file-url nil}
                 {:name "clojure.lang.Compiler$InvokeExpr/eval", :file "Compiler.java", :line 3702, :class "clojure.lang.Compiler$InvokeExpr", :method "eval", :type :java, :flags #{:tooling :java}, :file-url nil}
                 {:name "clojure.lang.Compiler$DefExpr/eval", :file "Compiler.java", :line 457, :class "clojure.lang.Compiler$DefExpr", :method "eval", :type :java, :flags #{:tooling :java}, :file-url nil}
                 {:name "clojure.lang.Compiler/eval", :file "Compiler.java", :line 7182, :class "clojure.lang.Compiler", :method "eval", :type :java, :flags #{:tooling :java}, :file-url nil}
                 {:name "clojure.lang.Compiler/load", :file "Compiler.java", :line 7636, :class "clojure.lang.Compiler", :method "load", :type :java, :flags #{:tooling :java}, :file-url nil}
                 {:name "clojure.lang.RT/loadResourceScript", :file "RT.java", :line 381, :class "clojure.lang.RT", :method "loadResourceScript", :type :java, :flags #{:java}, :file-url nil}
                 {:name "clojure.lang.RT/loadResourceScript", :file "RT.java", :line 372, :class "clojure.lang.RT", :method "loadResourceScript", :type :java, :flags #{:dup :java}, :file-url nil}
                 {:name "clojure.lang.RT/load", :file "RT.java", :line 459, :class "clojure.lang.RT", :method "load", :type :java, :flags #{:java}, :file-url nil}
                 {:name "clojure.lang.RT/load", :file "RT.java", :line 424, :class "clojure.lang.RT", :method "load", :type :java, :flags #{:dup :java}, :file-url nil}
                 {:fn "load/fn", :method "invoke", :ns "clojure.core", :name "clojure.core$load$fn__6839/invoke", :file "core.clj", :type :clj, :file-url "jar:file:/home/andreas/.m2/repository/org/clojure/clojure/1.10.1/clojure-1.10.1.jar!/clojure/core.clj", :line 6126, :var "clojure.core/load", :class "clojure.core$load$fn__6839", :flags #{:clj}}
                 {:fn "load", :method "invokeStatic", :ns "clojure.core", :name "clojure.core$load/invokeStatic", :file "core.clj", :type :clj, :file-url "jar:file:/home/andreas/.m2/repository/org/clojure/clojure/1.10.1/clojure-1.10.1.jar!/clojure/core.clj", :line 6125, :var "clojure.core/load", :class "clojure.core$load", :flags #{:clj}}
                 {:fn "load", :method "doInvoke", :ns "clojure.core", :name "clojure.core$load/doInvoke", :file "core.clj", :type :clj, :file-url "jar:file:/home/andreas/.m2/repository/org/clojure/clojure/1.10.1/clojure-1.10.1.jar!/clojure/core.clj", :line 6109, :var "clojure.core/load", :class "clojure.core$load", :flags #{:clj}}
                 {:name "clojure.lang.RestFn/invoke", :file "RestFn.java", :line 408, :class "clojure.lang.RestFn", :method "invoke", :type :java, :flags #{:java}, :file-url nil}
                 {:fn "load-one", :method "invokeStatic", :ns "clojure.core", :name "clojure.core$load_one/invokeStatic", :file "core.clj", :type :clj, :file-url "jar:file:/home/andreas/.m2/repository/org/clojure/clojure/1.10.1/clojure-1.10.1.jar!/clojure/core.clj", :line 5908, :var "clojure.core/load-one", :class "clojure.core$load_one", :flags #{:clj}}
                 {:fn "load-one", :method "invoke", :ns "clojure.core", :name "clojure.core$load_one/invoke", :file "core.clj", :type :clj, :file-url "jar:file:/home/andreas/.m2/repository/org/clojure/clojure/1.10.1/clojure-1.10.1.jar!/clojure/core.clj", :line 5903, :var "clojure.core/load-one", :class "clojure.core$load_one", :flags #{:clj}}
                 {:fn "load-lib/fn", :method "invoke", :ns "clojure.core", :name "clojure.core$load_lib$fn__6780/invoke", :file "core.clj", :type :clj, :file-url "jar:file:/home/andreas/.m2/repository/org/clojure/clojure/1.10.1/clojure-1.10.1.jar!/clojure/core.clj", :line 5948, :var "clojure.core/load-lib", :class "clojure.core$load_lib$fn__6780", :flags #{:clj}}
                 {:fn "load-lib", :method "invokeStatic", :ns "clojure.core", :name "clojure.core$load_lib/invokeStatic", :file "core.clj", :type :clj, :file-url "jar:file:/home/andreas/.m2/repository/org/clojure/clojure/1.10.1/clojure-1.10.1.jar!/clojure/core.clj", :line 5947, :var "clojure.core/load-lib", :class "clojure.core$load_lib", :flags #{:clj}}
                 {:fn "load-lib", :method "doInvoke", :ns "clojure.core", :name "clojure.core$load_lib/doInvoke", :file "core.clj", :type :clj, :file-url "jar:file:/home/andreas/.m2/repository/org/clojure/clojure/1.10.1/clojure-1.10.1.jar!/clojure/core.clj", :line 5928, :var "clojure.core/load-lib", :class "clojure.core$load_lib", :flags #{:clj}}
                 {:name "clojure.lang.RestFn/applyTo", :file "RestFn.java", :line 142, :class "clojure.lang.RestFn", :method "applyTo", :type :java, :flags #{:java}, :file-url nil}
                 {:fn "apply", :method "invokeStatic", :ns "clojure.core", :name "clojure.core$apply/invokeStatic", :file "core.clj", :type :clj, :file-url "jar:file:/home/andreas/.m2/repository/org/clojure/clojure/1.10.1/clojure-1.10.1.jar!/clojure/core.clj", :line 667, :var "clojure.core/apply", :class "clojure.core$apply", :flags #{:clj}}
                 {:fn "load-libs", :method "invokeStatic", :ns "clojure.core", :name "clojure.core$load_libs/invokeStatic", :file "core.clj", :type :clj, :file-url "jar:file:/home/andreas/.m2/repository/org/clojure/clojure/1.10.1/clojure-1.10.1.jar!/clojure/core.clj", :line 5985, :var "clojure.core/load-libs", :class "clojure.core$load_libs", :flags #{:clj}}
                 {:fn "load-libs", :method "doInvoke", :ns "clojure.core", :name "clojure.core$load_libs/doInvoke", :file "core.clj", :type :clj, :file-url "jar:file:/home/andreas/.m2/repository/org/clojure/clojure/1.10.1/clojure-1.10.1.jar!/clojure/core.clj", :line 5969, :var "clojure.core/load-libs", :class "clojure.core$load_libs", :flags #{:clj}}
                 {:name "clojure.lang.RestFn/applyTo", :file "RestFn.java", :line 137, :class "clojure.lang.RestFn", :method "applyTo", :type :java, :flags #{:java}, :file-url nil}
                 {:fn "apply", :method "invokeStatic", :ns "clojure.core", :name "clojure.core$apply/invokeStatic", :file "core.clj", :type :clj, :file-url "jar:file:/home/andreas/.m2/repository/org/clojure/clojure/1.10.1/clojure-1.10.1.jar!/clojure/core.clj", :line 667, :var "clojure.core/apply", :class "clojure.core$apply", :flags #{:clj}}
                 {:fn "require", :method "invokeStatic", :ns "clojure.core", :name "clojure.core$require/invokeStatic", :file "core.clj", :type :clj, :file-url "jar:file:/home/andreas/.m2/repository/org/clojure/clojure/1.10.1/clojure-1.10.1.jar!/clojure/core.clj", :line 6007, :var "clojure.core/require", :class "clojure.core$require", :flags #{:clj}}
                 {:fn "require", :method "doInvoke", :ns "clojure.core", :name "clojure.core$require/doInvoke", :file "core.clj", :type :clj, :file-url "jar:file:/home/andreas/.m2/repository/org/clojure/clojure/1.10.1/clojure-1.10.1.jar!/clojure/core.clj", :line 6007, :var "clojure.core/require", :class "clojure.core$require", :flags #{:dup :clj}}
                 {:name "clojure.lang.RestFn/invoke", :file "RestFn.java", :line 805, :class "clojure.lang.RestFn", :method "invoke", :type :java, :flags #{:java}, :file-url nil}
                 {:fn "eval96277/loading--auto--", :method "invoke", :ns "dynalloc.chevvy", :name "dynalloc.chevvy$eval96277$loading__6721__auto____96278/invoke", :file "NO_SOURCE_FILE", :type :clj, :file-url nil, :line 1, :var "dynalloc.chevvy/eval96277", :class "dynalloc.chevvy$eval96277$loading__6721__auto____96278", :flags #{:repl :clj}}
                 {:fn "eval96277", :method "invokeStatic", :ns "dynalloc.chevvy", :name "dynalloc.chevvy$eval96277/invokeStatic", :file "NO_SOURCE_FILE", :type :clj, :file-url nil, :line 1, :var "dynalloc.chevvy/eval96277", :class "dynalloc.chevvy$eval96277", :flags #{:dup :repl :clj}}
                 {:fn "eval96277", :method "invoke", :ns "dynalloc.chevvy", :name "dynalloc.chevvy$eval96277/invoke", :file "NO_SOURCE_FILE", :type :clj, :file-url nil, :line 1, :var "dynalloc.chevvy/eval96277", :class "dynalloc.chevvy$eval96277", :flags #{:dup :repl :clj}}
                 {:name "clojure.lang.Compiler/eval", :file "Compiler.java", :line 7177, :class "clojure.lang.Compiler", :method "eval", :type :java, :flags #{:tooling :java}, :file-url nil}
                 {:name "clojure.lang.Compiler/eval", :file "Compiler.java", :line 7166, :class "clojure.lang.Compiler", :method "eval", :type :java, :flags #{:dup :tooling :java}, :file-url nil}
                 {:name "clojure.lang.Compiler/eval", :file "Compiler.java", :line 7132, :class "clojure.lang.Compiler", :method "eval", :type :java, :flags #{:dup :tooling :java}, :file-url nil}
                 {:fn "eval", :method "invokeStatic", :ns "clojure.core", :name "clojure.core$eval/invokeStatic", :file "core.clj", :type :clj, :file-url "jar:file:/home/andreas/.m2/repository/org/clojure/clojure/1.10.1/clojure-1.10.1.jar!/clojure/core.clj", :line 3214, :var "clojure.core/eval", :class "clojure.core$eval", :flags #{:clj}}
                 {:fn "eval", :method "invoke", :ns "clojure.core", :name "clojure.core$eval/invoke", :file "core.clj", :type :clj, :file-url "jar:file:/home/andreas/.m2/repository/org/clojure/clojure/1.10.1/clojure-1.10.1.jar!/clojure/core.clj", :line 3210, :var "clojure.core/eval", :class "clojure.core$eval", :flags #{:clj}}
                 {:fn "repl/read-eval-print/fn", :method "invoke", :ns "clojure.main", :name "clojure.main$repl$read_eval_print__9086$fn__9089/invoke", :file "main.clj", :type :clj, :file-url "jar:file:/home/andreas/.m2/repository/org/clojure/clojure/1.10.1/clojure-1.10.1.jar!/clojure/main.clj", :line 437, :var "clojure.main/repl", :class "clojure.main$repl$read_eval_print__9086$fn__9089", :flags #{:clj}}
                 {:fn "repl/read-eval-print", :method "invoke", :ns "clojure.main", :name "clojure.main$repl$read_eval_print__9086/invoke", :file "main.clj", :type :clj, :file-url "jar:file:/home/andreas/.m2/repository/org/clojure/clojure/1.10.1/clojure-1.10.1.jar!/clojure/main.clj", :line 437, :var "clojure.main/repl", :class "clojure.main$repl$read_eval_print__9086", :flags #{:dup :clj}}
                 {:fn "repl/fn", :method "invoke", :ns "clojure.main", :name "clojure.main$repl$fn__9095/invoke", :file "main.clj", :type :clj, :file-url "jar:file:/home/andreas/.m2/repository/org/clojure/clojure/1.10.1/clojure-1.10.1.jar!/clojure/main.clj", :line 458, :var "clojure.main/repl", :class "clojure.main$repl$fn__9095", :flags #{:clj}}
                 {:fn "repl", :method "invokeStatic", :ns "clojure.main", :name "clojure.main$repl/invokeStatic", :file "main.clj", :type :clj, :file-url "jar:file:/home/andreas/.m2/repository/org/clojure/clojure/1.10.1/clojure-1.10.1.jar!/clojure/main.clj", :line 458, :var "clojure.main/repl", :class "clojure.main$repl", :flags #{:dup :clj}}
                 {:fn "repl", :method "doInvoke", :ns "clojure.main", :name "clojure.main$repl/doInvoke", :file "main.clj", :type :clj, :file-url "jar:file:/home/andreas/.m2/repository/org/clojure/clojure/1.10.1/clojure-1.10.1.jar!/clojure/main.clj", :line 368, :var "clojure.main/repl", :class "clojure.main$repl", :flags #{:clj}}
                 {:name "clojure.lang.RestFn/invoke", :file "RestFn.java", :line 1523, :class "clojure.lang.RestFn", :method "invoke", :type :java, :flags #{:java}, :file-url nil}
                 {:fn "evaluate", :method "invokeStatic", :ns "nrepl.middleware.interruptible-eval", :name "nrepl.middleware.interruptible_eval$evaluate/invokeStatic", :file "interruptible_eval.clj", :type :clj, :file-url "jar:file:/home/andreas/.m2/repository/nrepl/nrepl/0.6.0/nrepl-0.6.0.jar!/nrepl/middleware/interruptible_eval.clj", :line 79, :var "nrepl.middleware.interruptible-eval/evaluate", :class "nrepl.middleware.interruptible_eval$evaluate", :flags #{:tooling :clj}}
                 {:fn "evaluate", :method "invoke", :ns "nrepl.middleware.interruptible-eval", :name "nrepl.middleware.interruptible_eval$evaluate/invoke", :file "interruptible_eval.clj", :type :clj, :file-url "jar:file:/home/andreas/.m2/repository/nrepl/nrepl/0.6.0/nrepl-0.6.0.jar!/nrepl/middleware/interruptible_eval.clj", :line 55, :var "nrepl.middleware.interruptible-eval/evaluate", :class "nrepl.middleware.interruptible_eval$evaluate", :flags #{:tooling :clj}}
                 {:fn "interruptible-eval/fn/fn", :method "invoke", :ns "nrepl.middleware.interruptible-eval", :name "nrepl.middleware.interruptible_eval$interruptible_eval$fn__24364$fn__24368/invoke", :file "interruptible_eval.clj", :type :clj, :file-url "jar:file:/home/andreas/.m2/repository/nrepl/nrepl/0.6.0/nrepl-0.6.0.jar!/nrepl/middleware/interruptible_eval.clj", :line 142, :var "nrepl.middleware.interruptible-eval/interruptible-eval", :class "nrepl.middleware.interruptible_eval$interruptible_eval$fn__24364$fn__24368", :flags #{:tooling :clj}}
                 {:name "clojure.lang.AFn/run", :file "AFn.java", :line 22, :class "clojure.lang.AFn", :method "run", :type :java, :flags #{:java}, :file-url nil} {:fn "session-exec/main-loop/fn", :method "invoke", :ns "nrepl.middleware.session", :name "nrepl.middleware.session$session_exec$main_loop__24465$fn__24469/invoke", :file "session.clj", :type :clj, :file-url "jar:file:/home/andreas/.m2/repository/nrepl/nrepl/0.6.0/nrepl-0.6.0.jar!/nrepl/middleware/session.clj", :line 171, :var "nrepl.middleware.session/session-exec", :class "nrepl.middleware.session$session_exec$main_loop__24465$fn__24469", :flags #{:tooling :clj}}
                 {:fn "session-exec/main-loop", :method "invoke", :ns "nrepl.middleware.session", :name "nrepl.middleware.session$session_exec$main_loop__24465/invoke", :file "session.clj", :type :clj, :file-url "jar:file:/home/andreas/.m2/repository/nrepl/nrepl/0.6.0/nrepl-0.6.0.jar!/nrepl/middleware/session.clj", :line 170, :var "nrepl.middleware.session/session-exec", :class "nrepl.middleware.session$session_exec$main_loop__24465", :flags #{:tooling :clj}}
                 {:name "clojure.lang.AFn/run", :file "AFn.java", :line 22, :class "clojure.lang.AFn", :method "run", :type :java, :flags #{:java}, :file-url nil} {:name "java.lang.Thread/run", :file "Thread.java", :line 748, :class "java.lang.Thread", :method "run", :type :java, :flags #{:java}, :file-url nil})})

(def value-msg
  {:session "7362f58e-b613-46f8-853c-efcd8b61a590"
   :id "d5d598e3-ec20-4bf1-b6b9-af6329ac58c1"
   :ns "dynalloc.chevvy"
   :value "\"{:value-response {:type :html, :content [:span {:class \\\"clj-nil\\\"} \\\"nil\\\"], :value \\\"nil\\\"}}\""})






;(println (s/explain :nrepl-msg/stacktrace-msg stacktrace-msg))


(deftest nrepl-specs-test
  (is (= true (s/valid? :nrepl-msg/stacktrace-msg stacktrace-msg))))




